name: Trigger docs rebuild on main branch push

on:
  push:
    branches:
      - main

jobs:
  trigger_docs_rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger documentation rebuild
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_AdQsPmL4x3EiuqOcmznskUrnKAf2/1cTZzHFdm2
